# Project information
site_name: 'Team Playbooks'
site_description: 'Start projects on the right foot and improve team dynamics with Plays. These free workshop resources are designed to integrate into your workflow, and can be facilitated by any team member at any level.'
site_author: 'Randy Rowland'
site_url: 'https://rowland007.github.io/team-playbooks/'

# Repository
repo_name: 'Randy Rowland'
repo_url: 'https://github.com/rowland007/team-playbooks'

# Copyright
copyright: 'Copyright &copy; 2022-2023 Randall Rowland<br>This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

# Navigation Menu
nav:
    - Introduction: 'index.md'
    - 4 Ls Retrospective: '4lsretro/index.md'
    - 5 Whys Analysis: '5whys/index.md'
    - Capacity Planning: 'capacity/index.md'
    - Change Management Kick-Off: 'changeman/index.md'
    - Clean Escalations: 'cleanesc/index.md'
    - Contextual Inquiry: 'contextualinqu/index.md'
    - Customer Interview: 'customerinter/index.md'
    - Customer Journey Mapping: 'customerjourmap/index.md'
    - DACI Decision-Making Framework: 'daciframe/index.md'
    - Demo Trust: 'demotrust/index.md'
    - Dependency Mapping: 'dependency/index.md'
    - Disruptive Brainstorming: 'disruptivebrain/index.md'
    - Elevator Pitch: 'elevator/index.md'
    - Empathy Mapping: 'empathymap/index.md'
    - End-to-End Demo: 'e2edemo/index.md'
    - Experience Canvas: 'experiencecan/index.md'
    - Feature Kick-Off: 'featurekick/index.md'
    - Get $#!t Done Day: 'getdoneday/index.md'
    - Goals, Signals, and Measures: 'goalsmeasures/index.md'
    - Health Monitor: 'healthmon/index.md'
    - IT Project Kick-Off: 'itprojectoff/index.md'
    - IT Project Poster: 'itprojectposter/index.md'
    - Icebreaker Activities: 'icebreaker/index.md'
    - Incident Response Communications: 'ircomms/index.md'
    - Incident Response Values: 'irvalues/index.md'
    - Inclusive Meetings: 'inclusivemeet/index.md'
    - Learning Circle: 'learningcircle/index.md'
    - Ludicrously Complex Software Projects: 'ludcomplexsoftware/index.md'
    - Mindmapping: 'mindmap/index.md'
    - My User Manual: 'userman/index.md'
    - Objectives and Key Results (OKRs): 'okr/index.md'
    - Premortem: 'premortem/index.md'
    - Prioritize Allthethings: 'allthethings/index.md'
    - Prioritize, as a Team: 'prioritizeteam/index.md'
    - Problem Framing: 'problemframe/index.md'
    - Project Kickoff: 'projectkickoff/index.md'
    - Project Poster: 'projectposter/index.md'
    - Retrospective: 'retro/index.md'
    - Ritual Reset: 'ritualreset/index.md'
    - Roles & Responsibilities: 'roles/index.md'
    - Sparring: 'sparring/index.md'
    - Stakeholder Communication: 'stakeholdercomm/index.md'
    - Stand-Ups: 'standup/index.md'
    - Team Connectedness: 'teamconnect/index.md'
    - Trade-Offs: 'tradeoffs/index.md'
    - Work Life Impact: 'worklifeimpact/index.md'
    - Working Agreements: 'workagreement/index.md'

# Configuration
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      cite: octicons/link-external-16
    logo: material/file-document-edit-outline

# Customization
extra:
  social:
    - icon: material/cloud
      link: https://randyrowland.me
    - icon: fontawesome/brands/github
      link: https://github.com/rowland007
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/randarxj7
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/randall-rowland-jr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/rowland007

# Extensions
markdown_extensions:
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - md_in_html
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - tables
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js